# Generated by Django 4.2.1 on 2023-05-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMenu',
            new_name='Menu',
        ),
    ]
