# Generated by Django 4.2.1 on 2023-05-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0003_reservations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
