# Generated by Django 4.2.1 on 2023-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0004_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(max_length=1500),
        ),
    ]
